encoding: utf-8
# standard jekyll configuration

permalink: /:title/
highlighter: rouge
exclude: ['Rakefile','config.rb', 'README.md','gems','node_modules','*.sketch',
          'Gemfile','Gemfile.*','Gruntfile.*','package.json','temp']
# markdown: rdiscount // kramdown : problem with tables // redcarpet: problem with more
markdown: kramdown

gems: [jekyll-admin]

# configuration required for some pages

domain: css.yoksel.ru
url: http://css.yoksel.ru/
title: Про CSS
title_markup: '<span class="item--about">Про</span> <span class="item--css">CSS</span>'
description: Articles about CSS
author: yoksel
email: yoksel@yandex.ru

# feedburner:
#   id: feedburnerid

github:
    username: github/yoksel

# disqus:
#     id:

excerpt_separator: <!--more-->

env: prod

topmenu:
- name: 'Главная'
  url: '/'
- name: 'О сайте'
  url: '/about/'

links_title: Ссылки по теме

links_docs:
- url: http://www.w3.org/
  name: W3C
- url: https://developer.mozilla.org/
  name: developer.mozilla.org
- url: http://docs.webplatform.org/
  name: docs.webplatform.org
- url: http://learn.javascript.ru/
  name: learn.javascript.ru

links_tools:
- url: https://github.com/
  name: GitHub
- url: http://gruntjs.com/
  name: Grunt
- url: http://codepen.io/
  name: Codepen
- url: http://jsbin.com
  name: JsBin
- url: http://caniuse.com/
  name: Caniuse
- url: http://css3clickchart.com/
  name: CSS3 Click Chart
- url: http://cssfontstack.com/
  name: CssFontStack
- url: http://www.google.com/fonts/
  name: Google.com/fonts
- url: http://leaverou.github.io/css-colors/
  name: Css.coloratum
- url: http://icomoon.io/
  name: Icomoon

links_blogs:
- url: http://lea.verou.me/
  name: Lea Verou
- url: http://nicolasgallagher.com/
  name: Nicolas Gallagher
- url: http://csswizardry.com/
  name: Csswizardry.com
- url: http://sarasoueidan.com/
  name: Sara Soueidan
- url: http://css-tricks.com
  name: Сss-tricks.com
- url: http://tympanus.net/codrops/
  name: Сodrops
- url: http://css-weekly.com/archives/
  name: CSS Weekly
- url: http://css-live.ru/
  name: CSS-Live
- url: http://frontender.info/
  name: Frontender Magazine
- url: http://frontendbabel.info/
  name: Frontend Babel

links_usefull:
- url: /pages/tablitsa-imenovanny-h-tsvetov
  name: Таблица именованных цветов
- url: http://yoksel.github.io/unicode-table/
  name: Символы юникода
- url: https://github.com/miripiruni/frontdesk
  name: Frontdesk
- url: http://yoksel.github.io/url-encoder/
  name: URL-encoder для SVG

links_profiles:
- url: https://twitter.com/yoksel
  name: 'yoksel'
- url: https://twitter.com/yoksel_en
  name: 'yoksel_en'
- url: https://github.com/yoksel
  name: github.com/yoksel
- url: https://www.npmjs.org/~yoksel
  name: npmjs.org/~yoksel
- url: http://codepen.io/yoksel/
  name: codepen.io/yoksel
- url: http://yoksel.livejournal.com/
  name: yoksel.livejournal.com
- url: http://journals-covers.livejournal.com/
  name: journals-covers.livejournal.com
- url: http://colourlovers.com/lover/yoksel
  name: colourlovers.com/lover/yoksel
